name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: jurplel/install-qt-action@v4
        with:
          version: "6.11.1"
          modules: qt5compat
          cache: true

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure
